package com.alpha.domain.entity

import com.alpha.domain.converter.VerificationStatusConverter
import com.alpha.domain.enums.VerificationStatus
import jakarta.persistence.Convert
import jakarta.persistence.CascadeType
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.FetchType
import jakarta.persistence.Index
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import java.math.BigDecimal

@Entity
@Table(
    name = "businesses",
    indexes = [
        Index(name = "businesses_region_id_idx", columnList = "region_id"),
        Index(name = "businesses_category_id_idx", columnList = "category_id"),
        Index(name = "businesses_verification_status_idx", columnList = "verification_status"),
        Index(name = "businesses_location_idx", columnList = "latitude,longitude"),
        Index(name = "businesses_slug_idx", columnList = "slug")
    ]
)
class BusinessEntity : BaseEntity() {
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = jakarta.persistence.ForeignKey(name = "fk_businesses_user"))
    var user: UserEntity? = null
    
    @Column(name = "name", nullable = false)
    var name: String = ""
    
    @Column(name = "slug", unique = true, nullable = false)
    var slug: String = ""
    
    @Column(name = "description")
    var description: String? = null
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", foreignKey = jakarta.persistence.ForeignKey(name = "fk_businesses_category"))
    var category: CategoryEntity? = null
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "region_id", nullable = false, foreignKey = jakarta.persistence.ForeignKey(name = "fk_businesses_region"))
    var region: RegionEntity? = null
    
    // Contact Information
    @Column(name = "email")
    var email: String? = null
    
    @Column(name = "phone")
    var phone: String? = null
    
    @Column(name = "website")
    var website: String? = null
    
    // Address
    @Column(name = "address_line1")
    var addressLine1: String? = null
    
    @Column(name = "address_line2")
    var addressLine2: String? = null
    
    @Column(name = "city")
    var city: String? = null
    
    @Column(name = "state")
    var state: String? = null
    
    @Column(name = "zip_code")
    var zipCode: String? = null
    
    @Column(name = "country")
    var country: String? = null
    
    @Column(name = "latitude", precision = 10, scale = 8)
    var latitude: BigDecimal? = null
    
    @Column(name = "longitude", precision = 11, scale = 8)
    var longitude: BigDecimal? = null
    
    // Business Details
    @Column(name = "logo_url")
    var logoUrl: String? = null
    
    @Column(name = "cover_image_url")
    var coverImageUrl: String? = null
    
    @Column(name = "is_verified", nullable = false)
    var isVerified: Boolean = false
    
    @Column(name = "is_active", nullable = false)
    var isActive: Boolean = true
    
    @Column(name = "is_featured", nullable = false)
    var isFeatured: Boolean = false
    
    @Convert(converter = VerificationStatusConverter::class)
    @Column(name = "verification_status", nullable = false)
    var verificationStatus: VerificationStatus = VerificationStatus.PENDING
    
    @Column(name = "service_points_count", nullable = false)
    var servicePointsCount: Int = 1
    
    // Full-text search column (generated by database)
    @Column(name = "name_description_tsv", insertable = false, updatable = false)
    var nameDescriptionTsv: String? = null
    
    // Relationships
    @OneToMany(mappedBy = "business", cascade = [CascadeType.ALL], orphanRemoval = true)
    var services: MutableSet<ServiceEntity> = mutableSetOf()
    
    @OneToMany(mappedBy = "business", cascade = [CascadeType.ALL], orphanRemoval = true)
    var appointments: MutableSet<AppointmentEntity> = mutableSetOf()
    
    @OneToMany(mappedBy = "business", cascade = [CascadeType.ALL], orphanRemoval = true)
    var reviews: MutableSet<ReviewEntity> = mutableSetOf()
    
    @OneToMany(mappedBy = "business", cascade = [CascadeType.ALL], orphanRemoval = true)
    var businessHours: MutableSet<BusinessHoursEntity> = mutableSetOf()
}